<%
  adapter = RailsStarter.db_adapter
  
  database_file = {
    "postgres" => "database.postgres.yml",
    "sqlite" => "database.sqlite.yml",
    "mysql" => "database.mysql.yml",
  }

  config_path = File.join(__dir__, database_file[adapter])
%>
<%= ERB.new(File.read(config_path)).result %>
