default: &default
  adapter: trilogy
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "rails_starter_development") %>
    schema_dump: schema.mysql.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "rails_starter_development_cable") %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.mysql.rb

test:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_TEST", "rails_starter_test") %>
    schema_dump: schema.mysql.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "rails_starter_test_cable") %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.mysql.rb

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "rails_starter_production") %>
    schema_dump: schema.mysql.rb
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CACHE", "rails_starter_production_cache") %>
    migrations_paths: db/cache_migrate
    schema_dump: cache_schema.mysql.rb
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_QUEUE", "rails_starter_production_queue") %>
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.mysql.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "rails_starter_production_cable") %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.mysql.rb
