default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "storage/development.sqlite3") %>
    schema_dump: schema.sqlite.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "storage/development_cable.sqlite3") %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.sqlite.rb

test:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_TEST", "storage/test.sqlite3") %>
    schema_dump: schema.sqlite.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "storage/test_cable.sqlite3") %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.sqlite.rb

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "storage/production.sqlite3") %>
    schema_dump: schema.sqlite.rb
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CACHE", "storage/production_cache.sqlite3") %>
    migrations_paths: db/cache_migrate
    schema_dump: cache_schema.sqlite.rb
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_QUEUE", "storage/production_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.sqlite.rb
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "storage/production_cable.sqlite3") %>
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.sqlite.rb
